/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusScreen.java
 *
 * Created on 24/11/2011, 16:25:11
 */
package bgu.csp.az.dev.ui;

import bc.dsl.SwingDSL;
import javax.swing.JPanel;

/**
 *
 * @author bennyl
 */
public class MessageScreen extends javax.swing.JPanel {

    public static enum MessageType {

        INFO,
        SUCCESS,
        FAIL;

        public String getIconName(MessageType type) {
            switch (type) {
                case FAIL:
                    return "fail-message";
                case SUCCESS:
                    return "success-message";
                case INFO:
                    return "info-message";

            }
            return "info-message";
        }

        public String getTypeText(MessageType type) {
            switch (type) {
                case FAIL:
                    return "ONOES!";
                case SUCCESS:
                    return "WHOOPY!";
                case INFO:
                    return "HMMM...";

            }


            return "UNKNOWN TYPE OF MESSAGE";
        }
    }

    /** Creates new form StatusScreen */
    public MessageScreen() {
        initComponents();
    }

    public MessageScreen(MessageType type, String data, String content) {
        initComponents();
        this.messageContentLabel.setText(content);
        this.messageDataLabel.setText(data);
        chooseIconAndType(type);
    }

    public MessageScreen(MessageType type, String data, JPanel content) {
        this.messageContentPanel = content;
        initComponents();
        this.messageDataLabel.setText(data);
    }

    private void chooseIconAndType(MessageType messageType) {
        this.typeLable.setText(messageType.getIconName(messageType));
        this.iconLabel.setIcon(SwingDSL.resIcon(messageType.getIconName(messageType)));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundDataScroll = new javax.swing.JScrollPane();
        roundView = new bgu.csp.az.dev.ui.RoundView();
        jPanel2 = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        typeLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        messageDataLabel = new javax.swing.JLabel();
        messageContentPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        messageContentLabel = new javax.swing.JLabel();

        roundDataScroll.setBorder(null);
        roundDataScroll.setViewportView(roundView);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/monitor.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(iconLabel, gridBagConstraints);

        typeLable.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        typeLable.setText("Something Went Wrong...");
        typeLable.setDoubleBuffered(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(typeLable, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(120, 120, 120));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel11.setBackground(new java.awt.Color(120, 120, 120));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Exception description : ");
        jPanel11.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        messageDataLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageDataLabel.setText("The actual description");
        jPanel11.add(messageDataLabel, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(jPanel11, gridBagConstraints);

        messageContentPanel.setBackground(new java.awt.Color(120, 120, 120));
        messageContentPanel.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("what can you do ?");
        messageContentPanel.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        messageContentLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageContentLabel.setText("The actual detail");
        messageContentPanel.add(messageContentLabel, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(messageContentPanel, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel messageContentLabel;
    private javax.swing.JPanel messageContentPanel;
    private javax.swing.JLabel messageDataLabel;
    private javax.swing.JScrollPane roundDataScroll;
    private bgu.csp.az.dev.ui.RoundView roundView;
    private javax.swing.JLabel typeLable;
    // End of variables declaration//GEN-END:variables
}
