/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * XMenuTreeCR.java
 *
 * Created on 03/07/2011, 02:04:55
 */
package bc.swing.pfrm.params.views.ext;

import bc.swing.models.GenericTreeModel.Node;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Component;
import javax.swing.JTree;
import javax.swing.border.LineBorder;
import javax.swing.tree.TreeCellRenderer;
import static bc.dsl.SwingDSL.*;

/**
 *
 * @author bennyl
 */
public class SimpleTreeRenderer extends javax.swing.JPanel implements TreeCellRenderer {

    public static final ImageIcon CLOSED_FOLDER = resIcon("menui/xcomp/img/blue-folder-horizontal.png");
    public static final ImageIcon OPEN_FOLDER = resIcon("menui/xcomp/img/blue-folder-horizontal-open.png");
    public static final LineBorder SELECTED_BORDER = new LineBorder(Color.LIGHT_GRAY, 1);
    public static final LineBorder UNSELECTED_BORDER = new LineBorder(Color.white, 1);
    private IconProvider leafIconProvider;

    /** Creates new form XMenuTreeCR */
    public SimpleTreeRenderer(IconProvider iprov) {
        initComponents();
        leafIconProvider = iprov;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 1));

        txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menui/xcomp/img/blue-folder-horizontal.png"))); // NOI18N
        txt.setText("jLabel1");
        add(txt);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getTreeCellRendererComponent(JTree tree, Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus) {

        Node n = (Node) value;
        if (n.isLeaf()) {
            txt.setIcon(leafIconProvider.getIcon(n.getData()));
        } else {
            if (expanded) {
                txt.setIcon(OPEN_FOLDER);
            } else {
                txt.setIcon(CLOSED_FOLDER);
            }
        }
        if (selected) {
            setBorder(SELECTED_BORDER);
        } else {
            setBorder(UNSELECTED_BORDER);
        }

        txt.setText(n.toString());

        return this;
    }
}
