/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PageForm.java
 *
 * Created on Sep 11, 2011, 12:37:56 PM
 */
package bc.swing.pfrm.layouts;

import bc.swing.pfrm.BaseParamModel;
import bc.swing.pfrm.Page;
import bc.swing.pfrm.PageView;
import bc.swing.pfrm.ano.ViewHints;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author BLutati
 */
public class FormLayout extends javax.swing.JPanel implements PageView {

    Page model;
    public Set<String> exclude;
    Color labelBackColor = new Color(245, 245, 245);
    private JPanel sidepan;
    private boolean colorLabels = true;
    private boolean heightTaken = false;
    private boolean takeAllHeight = false;

    /** Creates new form PageForm */
    public FormLayout() {
        initComponents();
        exclude = new HashSet<String>();
    }

    public void setTakeAllHeight(boolean takeAllHeight) {
        this.takeAllHeight = takeAllHeight;
    }

    public boolean isTakeAllHeight() {
        return takeAllHeight;
    }

    public void setColorLabels(boolean colorLabels) {
        this.colorLabels = colorLabels;
        if (sidepan != null) {
            sidepan.setOpaque(colorLabels);
        }
    }

    public boolean isColorLabels() {
        return colorLabels;
    }

    public void setLabelBackColor(Color labelBackColor) {
        this.labelBackColor = labelBackColor;
        if (sidepan != null) {
            sidepan.setBackground(labelBackColor);
            repaint();
        }

    }

    /**
     * must be called before setModel();
     * @param fields
     */
    public void excludeParams(String... fields) {
        exclude.addAll(Arrays.asList(fields));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void setPage(Page model) {
        this.model = model;
        List<BaseParamModel> params = model.getParams();
        for (BaseParamModel param : params) {
            if (!exclude.contains(param.getName())) {
                String[] nameLR = param.getName().split("\\$\\$");

                if (nameLR[0].startsWith("#")) {
                    addValueView(param.getDefaultView(), param.getViewHints(), 3);
                } else {
                    addLabel(nameLR[0], param.getIcon());
                    addValueView(param.getDefaultView(), param.getViewHints(), 3 - nameLR.length);
                    if (nameLR.length > 1) {
                        addTrailLabel(nameLR[1], null);
                    }

                }
            }
        }

        sealLayout();
        validate();
        repaint();
    }

    private void addLabel(String name, ImageIcon icon) {
        JLabel lbl = new JLabel();
        lbl.setText(name);
        lbl.setIcon(icon);
//        lbl.setVerticalAlignment(SwingConstants.TOP);
        GridBagConstraints cons = new GridBagConstraints();
        cons.fill = GridBagConstraints.BOTH;
        cons.gridx = 0;
//        cons.anchor = GridBagConstraints.NORTH;
        cons.insets = new Insets(5, 5, 0, 5);
        add(lbl, cons);
    }

    private void addTrailLabel(String name, ImageIcon icon) {
        JLabel lbl = new JLabel();
        lbl.setText(name);
        lbl.setIcon(icon);
//        lbl.setVerticalAlignment(SwingConstants.TOP);
        GridBagConstraints cons = new GridBagConstraints();
        cons.fill = GridBagConstraints.BOTH;
        cons.gridx = 2;
        cons.insets = new Insets(5, 5, 0, 5);
        add(lbl, cons);
    }

    private void addValueView(JComponent defaultView, ViewHints viewHints, int columns) {
        GridBagConstraints cons = new GridBagConstraints();
        if (columns == 3) {
            cons.gridx = 0;
        } else {
            cons.gridx = 1;
        }
        cons.insets = new Insets(5, 5, 0, 5);
        cons.weightx = 1;
        cons.gridwidth = columns;
        cons.fill = GridBagConstraints.BOTH;
        if (viewHints.heightExpandPrecentage() > 0) {
            cons.weighty = 100.0 / viewHints.heightExpandPrecentage();
            heightTaken = true;
        }

        add(defaultView, cons);
    }

    private void sealLayout() {
        sidepan = new JPanel();
        sidepan.setBackground(labelBackColor);
        sidepan.setOpaque(isColorLabels());
        GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 500;
        gbc.fill = java.awt.GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 0, 0, 0);

        if (!heightTaken && takeAllHeight) {
            gbc.weighty = 1;
        }

        add(sidepan, gbc);
    }

    public void onDispose() {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
