/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SideCenterLayout.java
 *
 * Created on Sep 11, 2011, 3:11:21 PM
 */
package bc.swing.pfrm.layouts;

import bc.swing.pfrm.Page;
import bc.swing.pfrm.PageView;
import bc.swing.pfrm.BaseParamModel;
import java.awt.BorderLayout;

/**
 *
 * @author BLutati
 */
public class SideSplitCenterLayout extends javax.swing.JPanel implements PageView {

    public static final String SIDE_ROLE = "SIDE";
    public static final String TOP_ROLE = "TOP";
    public static final String BOTTOM_ROLE = "BOTTOM";

    Page model;

    /** Creates new form SideCenterLayout */
    public SideSplitCenterLayout() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        backPan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jGradientPanel1 = new bc.swing.comp.JGradientPanel();
        sideCaptionLabel = new javax.swing.JLabel();
        side = new javax.swing.JPanel();
        center = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jGradientPanel3 = new bc.swing.comp.JGradientPanel();
        bottomCaptionLabel = new javax.swing.JLabel();
        buttom = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jGradientPanel2 = new bc.swing.comp.JGradientPanel();
        topCaptionLabel = new javax.swing.JLabel();
        top = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setResizeWeight(0.1);

        backPan.setBackground(new java.awt.Color(255, 255, 255));
        backPan.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jGradientPanel1.setBackground(new java.awt.Color(177, 177, 177));
        jGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jGradientPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        sideCaptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        sideCaptionLabel.setText("jLabel1");
        jGradientPanel1.add(sideCaptionLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel3.add(jGradientPanel1, gridBagConstraints);

        side.setBackground(new java.awt.Color(255, 255, 255));
        side.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(side, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        backPan.add(jPanel3, gridBagConstraints);

        jSplitPane1.setLeftComponent(backPan);

        center.setBackground(new java.awt.Color(255, 255, 255));
        center.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setBorder(null);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jGradientPanel3.setBackground(new java.awt.Color(177, 177, 177));
        jGradientPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jGradientPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        bottomCaptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        bottomCaptionLabel.setText("jLabel1");
        jGradientPanel3.add(bottomCaptionLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel5.add(jGradientPanel3, gridBagConstraints);

        buttom.setBackground(new java.awt.Color(255, 255, 255));
        buttom.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(buttom, gridBagConstraints);

        jSplitPane2.setRightComponent(jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jGradientPanel2.setBackground(new java.awt.Color(177, 177, 177));
        jGradientPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jGradientPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        topCaptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        topCaptionLabel.setText("jLabel1");
        jGradientPanel2.add(topCaptionLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel4.add(jGradientPanel2, gridBagConstraints);

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(top, gridBagConstraints);

        jSplitPane2.setLeftComponent(jPanel4);

        center.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(center);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPan;
    private javax.swing.JLabel bottomCaptionLabel;
    private javax.swing.JPanel buttom;
    private javax.swing.JPanel center;
    private bc.swing.comp.JGradientPanel jGradientPanel1;
    private bc.swing.comp.JGradientPanel jGradientPanel2;
    private bc.swing.comp.JGradientPanel jGradientPanel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel side;
    private javax.swing.JLabel sideCaptionLabel;
    private javax.swing.JPanel top;
    private javax.swing.JLabel topCaptionLabel;
    // End of variables declaration//GEN-END:variables

    public void setPage(Page model) {
        this.model = model;
        final BaseParamModel sp = model.getParamsWithRole(SIDE_ROLE).get(0);
        final BaseParamModel tp = model.getParamsWithRole(TOP_ROLE).get(0);
        final BaseParamModel bp = model.getParamsWithRole(BOTTOM_ROLE).get(0);

        side.add(sp.getDefaultView(), BorderLayout.CENTER);
        top.add(tp.getDefaultView(), BorderLayout.CENTER);
        buttom.add(bp.getDefaultView(), BorderLayout.CENTER);

        sideCaptionLabel.setText(sp.getName());
        sideCaptionLabel.setIcon(sp.getIcon());

        topCaptionLabel.setText(tp.getName());
        topCaptionLabel.setIcon(tp.getIcon());

        bottomCaptionLabel.setText(bp.getName());
        bottomCaptionLabel.setIcon(bp.getIcon());

        validate();
        repaint();

    }

    public void onDispose() {
    }
}
