/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SideCenterLayout.java
 *
 * Created on Sep 11, 2011, 3:11:21 PM
 */
package bc.swing.pfrm.layouts;

import bc.swing.pfrm.BaseParamModel;
import bc.swing.pfrm.Page;
import bc.swing.pfrm.PageLayout;
import bc.swing.pfrm.ano.Param;
import bc.swing.pfrm.FieldParamModel;
import java.awt.BorderLayout;
import java.util.List;
import javax.naming.directory.InvalidAttributesException;

/**
 *
 * @author BLutati
 */
public class SideCenterLayout extends javax.swing.JPanel implements PageLayout {

    public static final String SIDE_ROLE = "SIDE";
    Page model;

    /** Creates new form SideCenterLayout */
    public SideCenterLayout() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        backPan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jGradientPanel1 = new bc.swing.comp.JGradientPanel();
        captionLabel = new javax.swing.JLabel();
        side = new javax.swing.JPanel();
        center = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setResizeWeight(0.1);

        backPan.setBackground(new java.awt.Color(255, 255, 255));
        backPan.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jGradientPanel1.setBackground(new java.awt.Color(177, 177, 177));
        jGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jGradientPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        captionLabel.setForeground(new java.awt.Color(255, 255, 255));
        captionLabel.setText("jLabel1");
        jGradientPanel1.add(captionLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel3.add(jGradientPanel1, gridBagConstraints);

        side.setBackground(new java.awt.Color(255, 255, 255));
        side.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(side, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        backPan.add(jPanel3, gridBagConstraints);

        jSplitPane1.setLeftComponent(backPan);

        center.setBackground(new java.awt.Color(255, 255, 255));
        center.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(center);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPan;
    private javax.swing.JLabel captionLabel;
    private javax.swing.JPanel center;
    private bc.swing.comp.JGradientPanel jGradientPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel side;
    // End of variables declaration//GEN-END:variables

    public void setPage(Page model) {
        this.model = model;
        List<BaseParamModel> params = model.getParams();
        BaseParamModel sideParam = null;
        for (BaseParamModel p : params) {
            if (p.getRole().equals(SIDE_ROLE)) {
                sideParam = p;
                break;
            }
        }

        if (sideParam == null) {
            throw new RuntimeException("cannot find param with side role.");
        }

        side.removeAll();
        side.add(sideParam.getDefaultView(), BorderLayout.CENTER);
        captionLabel.setText(sideParam.getName());
        captionLabel.setIcon(sideParam.getIcon());
        
        if (params.size() == 2) {
            if (params.get(0).getRole().equals(SIDE_ROLE)) {
                center.add(params.get(1).getDefaultView(), BorderLayout.CENTER);
            } else {
                center.add(params.get(1).getDefaultView(), BorderLayout.CENTER);
            }
        } else {
            FormLayout fl = new FormLayout();
            fl.excludeParams(sideParam.getName());
            fl.setPage(model);
            center.add(fl, BorderLayout.CENTER);
        }

        validate();
        repaint();

    }

    public void onDispose() {
    }
}
