/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StackLayout.java
 *
 * Created on 13/09/2011, 02:54:00
 */
package bc.swing.pfrm.layouts;

import bc.swing.pfrm.BaseParamModel;
import bc.swing.pfrm.Page;
import bc.swing.pfrm.PageView;
import bc.swing.pfrm.ano.ViewHints;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.List;

/**
 *
 * @author bennyl
 */
public class StackLayout extends javax.swing.JPanel implements PageView {

    /** Creates new form StackLayout */
    public StackLayout() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setPage(Page model) {
        List<BaseParamModel> params = model.getParams();
        for (BaseParamModel p : params) {
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.fill = GridBagConstraints.BOTH;
            gbc.gridx = 0;
            gbc.weightx = 1.0;
            ViewHints vh = p.getViewHints();
            if (vh!= null && vh.heightExpandPrecentage() > 0) {
                gbc.weighty = 100.0 / vh.heightExpandPrecentage();
            }
            
            gbc.insets = new Insets(0, 5, 5, 5);
            add(p.getDefaultView(), gbc);
        }
        
        validate();
        repaint();
    }

    public void onDispose() {
    }
}
