/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SideCenterLayout.java
 *
 * Created on Sep 11, 2011, 3:11:21 PM
 */
package bc.swing.pfrm.layouts;

import bc.swing.pfrm.Page;
import bc.swing.pfrm.PageLayout;
import bc.swing.pfrm.BaseParamModel;
import bc.swing.pfrm.FieldParamModel;
import java.awt.BorderLayout;
import java.util.List;

/**
 *
 * @author BLutati
 */
public class TopBottomLayout extends javax.swing.JPanel implements PageLayout {

    public static final String TOP_ROLE = "TOP";
    public static final String BOTTOM_ROLE = "BOTTOM";
    Page model;

    /** Creates new form SideCenterLayout */
    public TopBottomLayout() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        backPan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        toptb = new bc.swing.comp.JCaptionToolbar();
        top = new javax.swing.JPanel();
        backPan1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btb = new bc.swing.comp.JCaptionToolbar();
        bottom = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);

        backPan.setBackground(new java.awt.Color(255, 255, 255));
        backPan.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(toptb, gridBagConstraints);

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel3.add(top, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        backPan.add(jPanel3, gridBagConstraints);

        jSplitPane1.setLeftComponent(backPan);

        backPan1.setBackground(new java.awt.Color(255, 255, 255));
        backPan1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(btb, gridBagConstraints);

        bottom.setBackground(new java.awt.Color(255, 255, 255));
        bottom.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel4.add(bottom, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        backPan1.add(jPanel4, gridBagConstraints);

        jSplitPane1.setRightComponent(backPan1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPan;
    private javax.swing.JPanel backPan1;
    private javax.swing.JPanel bottom;
    private bc.swing.comp.JCaptionToolbar btb;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel top;
    private bc.swing.comp.JCaptionToolbar toptb;
    // End of variables declaration//GEN-END:variables

    public void setPage(Page model) {
        this.model = model;
        final List<BaseParamModel> tpl = model.getParamsWithRole(TOP_ROLE);
        if (!tpl.isEmpty()) {
            BaseParamModel tp = tpl.get(0);
            top.add(tp.getDefaultView(), BorderLayout.CENTER);
            toptb.setCaption(tp.getName());
            toptb.setCaptionIcon(tp.getIcon());
            toptb.setActions(tp.getActions());
        }


        final List<BaseParamModel> bpl = model.getParamsWithRole(BOTTOM_ROLE);
        if (!bpl.isEmpty()) {
            BaseParamModel bp = bpl.get(0);
            bottom.add(bp.getDefaultView(), BorderLayout.CENTER);
            btb.setCaption(bp.getName());
            btb.setCaptionIcon(bp.getIcon());
            btb.setActions(bp.getActions());
        }
        validate();
        repaint();

    }

    public void onDispose() {
    }
}
