/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PagePV.java
 *
 * Created on Sep 11, 2011, 3:42:00 PM
 */
package bc.swing.pfrm.views;

import bc.swing.pfrm.Model;
import bc.swing.pfrm.Page;
import bc.swing.pfrm.ano.ViewHints;
import bc.swing.pfrm.BaseParamModel;
import bc.swing.pfrm.ParamView;
import java.awt.BorderLayout;
import java.awt.Dimension;

/**
 *
 * @author BLutati
 */
public class PagePV extends javax.swing.JPanel implements ParamView {

    Page p;

    /** Creates new form PagePV */
    public PagePV() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void setParam(BaseParamModel model) {
        final ViewHints vh = model.getViewHints();
        if (vh != null){
            if (vh.minimumHeight() > 0){
                setMinimumSize(new Dimension(getMinimumSize().width, vh.minimumHeight()));
            }
        }
        
        Model o = (Model) model.getValue();
        if (o != null) {
            p = Page.get(o);
            removeAll();
            add(p.getView(), BorderLayout.CENTER);
        }
        validate();
        repaint();
    }

    public void reflectChangesToParam(BaseParamModel to) {
        p.syncParametersFromView();
    }

    public void onChange(BaseParamModel source, Object newValue, Object deltaHint) {
        setParam(source);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
