/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnalayzedTableView.java
 *
 * Created on 22/11/2011, 11:51:36
 */
package bgu.csp.az.dev.pui.stat;

import bam.utils.ui.mvc.DataExtractor;
import bam.utils.ui.mvc.GenericTableModel;
import bc.swing.pfrm.Parameter;
//import bc.swing.pfrm.ParamView;
import bgu.csp.az.api.infra.stat.VisualModel;
import bgu.csp.az.api.infra.stat.vmod.BarVisualModel;
import bgu.csp.az.api.infra.stat.vmod.LineVisualModel;
import bgu.csp.az.api.infra.stat.vmod.PieVisualModel;
import java.util.LinkedList;
import java.util.Map.Entry;

/**
 *
 * @author bennyl
 */
public class AnalayzedTableView extends javax.swing.JPanel {

    /** Creates new form AnalayzedTableView */
    public AnalayzedTableView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

//    @Override
    public void setParam(Parameter param) {
        onChange(param, param.getValue(), null);
    }

//    @Override
    public void reflectChangesToParam(Parameter to) {
//        throw new UnsupportedOperationException("Not supported yet.");
    }

//    @Override
    public void onChange(Parameter param, Object newValue, Object deltaHint) {
        VisualModel model = (VisualModel) param.getValue();

        if (model instanceof LineVisualModel) {
            setLine((LineVisualModel) model);
        } else if (model instanceof PieVisualModel) {
            setPie(model);
        } else if (model instanceof BarVisualModel) {
            setBar(model);
        }
    }

    private void setLine(final LineVisualModel model) {
        GenericTableModel<Entry<Double, Double>> tabmodel = new GenericTableModel<Entry<Double, Double>>(new DataExtractor<Entry<Double, Double>>(model.getxAxisName(), model.getyAxisName()) {

            @Override
            public Object getData(String dataName, Entry<Double, Double> from) {
                if (dataName.equals(model.getxAxisName())) {
                    return from.getKey();
                } else {
                    return from.getValue();
                }
            }
        });

        tabmodel.fillWith(new LinkedList<Entry<Double, Double>>(model.getValues().entrySet()));
        table.setModel(tabmodel);
    }

    private void setPie(VisualModel model) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    private void setBar(VisualModel model) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
}
