/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProblemSelectionDialog.java
 *
 * Created on 28/08/2011, 02:22:05
 */
package bgu.csp.az.dev.ui.dialogs;

import java.io.File;

/**
 *
 * @author bennyl
 */
public class ProblemSelectionDialog extends javax.swing.JDialog {

    ProblemSelectionModel model;
    
    /** Creates new form ProblemSelectionDialog */
    public ProblemSelectionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setModel(ProblemSelectionModel model){
        this.model = model;
        plist.setModel(model.getProblemsModel());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mattePainter1 = new org.jdesktop.swingx.painter.MattePainter();
        jPanel1 = new javax.swing.JPanel();
        captionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        plist = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        jXHyperlink2 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink4 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink3 = new org.jdesktop.swingx.JXHyperlink();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        captionLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        captionLabel.setForeground(new java.awt.Color(51, 51, 51));
        captionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/gnome-glchess.png"))); // NOI18N
        captionLabel.setText("Faild Problem Selection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(captionLabel, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Below are problems that was faild in previous executions - select the one you want to debug");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        plist.setBackground(new java.awt.Color(245, 245, 245));
        plist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 245, 245), 5));
        plist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        plist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                plistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(plist);

        contentPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(contentPanel, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(230, 230, 230));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jXHyperlink2.setBackground(new java.awt.Color(245, 245, 245));
        jXHyperlink2.setForeground(new java.awt.Color(0, 51, 204));
        jXHyperlink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/tick-circle.png"))); // NOI18N
        jXHyperlink2.setText("Select and start");
        jXHyperlink2.setClickedColor(new java.awt.Color(0, 51, 204));
        jXHyperlink2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink2ActionPerformed(evt);
            }
        });
        jPanel7.add(jXHyperlink2);

        jXHyperlink4.setBackground(new java.awt.Color(245, 245, 245));
        jXHyperlink4.setForeground(new java.awt.Color(0, 51, 204));
        jXHyperlink4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/full-run.png"))); // NOI18N
        jXHyperlink4.setText("Debug full test file");
        jXHyperlink4.setClickedColor(new java.awt.Color(0, 51, 204));
        jXHyperlink4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink4ActionPerformed(evt);
            }
        });
        jPanel7.add(jXHyperlink4);

        jXHyperlink3.setForeground(new java.awt.Color(0, 51, 204));
        jXHyperlink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/cross-circle.png"))); // NOI18N
        jXHyperlink3.setText("Cancel");
        jXHyperlink3.setClickedColor(new java.awt.Color(0, 51, 204));
        jXHyperlink3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink3ActionPerformed(evt);
            }
        });
        jPanel7.add(jXHyperlink3);

        getContentPane().add(jPanel7, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXHyperlink2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink2ActionPerformed
        setVisible(false);
}//GEN-LAST:event_jXHyperlink2ActionPerformed

    private void jXHyperlink3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink3ActionPerformed
        model.setSelectedProblemFile(null);
        setVisible(false);
}//GEN-LAST:event_jXHyperlink3ActionPerformed

    private void plistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_plistValueChanged
        model.setSelectedProblemFile((File)plist.getSelectedValue());
    }//GEN-LAST:event_plistValueChanged

    private void jXHyperlink4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink4ActionPerformed
        model.setDebugFullTest(true);
        setVisible(false);
    }//GEN-LAST:event_jXHyperlink4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ProblemSelectionDialog dialog = new ProblemSelectionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel captionLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink4;
    private org.jdesktop.swingx.painter.MattePainter mattePainter1;
    private javax.swing.JList plist;
    // End of variables declaration//GEN-END:variables
}
