package bgu.dcr.az.lab.data;
// Generated 21:13:44 25/05/2012 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articles generated by hbm2java
 */
public class Articles  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String title;
     private byte[] content;
     private Date creationDate;
     private int viewedAmount;
     private boolean type;
     private Set commentses = new HashSet(0);

    public Articles() {
    }

	
    public Articles(Users users, String title, Date creationDate, int viewedAmount, boolean type) {
        this.users = users;
        this.title = title;
        this.creationDate = creationDate;
        this.viewedAmount = viewedAmount;
        this.type = type;
    }
    public Articles(Users users, String title, byte[] content, Date creationDate, int viewedAmount, boolean type, Set commentses) {
       this.users = users;
       this.title = title;
       this.content = content;
       this.creationDate = creationDate;
       this.viewedAmount = viewedAmount;
       this.type = type;
       this.commentses = commentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public int getViewedAmount() {
        return this.viewedAmount;
    }
    
    public void setViewedAmount(int viewedAmount) {
        this.viewedAmount = viewedAmount;
    }
    public boolean isType() {
        return this.type;
    }
    
    public void setType(boolean type) {
        this.type = type;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


