package bgu.dcr.az.lab.data;
// Generated May 30, 2012 7:41:57 PM by Hibernate Tools 3.2.1.GA



/**
 * Tags generated by hbm2java
 */
public class Tags  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Tags() {
    }

    public Tags(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


