package bgu.dcr.az.lab.data;
// Generated 21:13:44 25/05/2012 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String password;
     private String name;
     private byte[] avatar;
     private boolean admin;
     private Set commentses = new HashSet(0);
     private Set articleses = new HashSet(0);

    public Users() {
    }

	
    public Users(String email, String password, String name, byte[] avatar, boolean admin) {
        this.email = email;
        this.password = password;
        this.name = name;
        this.avatar = avatar;
        this.admin = admin;
    }
    public Users(String email, String password, String name, byte[] avatar, boolean admin, Set commentses, Set articleses) {
       this.email = email;
       this.password = password;
       this.name = name;
       this.avatar = avatar;
       this.admin = admin;
       this.commentses = commentses;
       this.articleses = articleses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getArticleses() {
        return this.articleses;
    }
    
    public void setArticleses(Set articleses) {
        this.articleses = articleses;
    }




}


