/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgressPV.java
 *
 * Created on 30/09/2011, 16:46:57
 */
package bc.swing.pfrm.params.views;

import bc.swing.pfrm.params.ParamModel;
import bc.swing.pfrm.params.ParamView;
import javax.swing.DefaultBoundedRangeModel;

/**
 *
 * @author bennyl
 */
public class ProgressPV extends javax.swing.JPanel implements ParamView {

    /** Creates new form ProgressPV */
    public ProgressPV() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbl = new javax.swing.JLabel();
        pb = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        lbl.setText("jLabel1");
        add(lbl, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(pb, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables

    public void setModel(ParamModel model) {
        DefaultBoundedRangeModel m = (DefaultBoundedRangeModel) model.getValue();
        pb.setModel(m);
        lbl.setText(model.getName());
        lbl.setIcon(model.getIcon());
    }

    public void reflectChanges(ParamModel to) {
//        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void onChange(ParamModel source, Object newValue, Object deltaHint) {
//        throw new UnsupportedOperationException("Not supported yet.");
    }
}
