/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScrollableStripeTree.java
 *
 * Created on 28/11/2011, 22:18:16
 */
package bc.ui.swing.trees;

/**
 *
 * @author bennyl
 */
public class ScrollableStripeTree extends javax.swing.JPanel {

    /** Creates new form ScrollableStripeTree */
    public ScrollableStripeTree() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stripeTree1 = new bc.ui.swing.trees.StripeTree();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportView(stripeTree1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private bc.ui.swing.trees.StripeTree stripeTree1;
    // End of variables declaration//GEN-END:variables
}
