/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScenarioPartView.java
 *
 * Created on 09/09/2011, 02:41:28
 */
package bgu.csp.az.dev.ui.canalyzers;

import bgu.csp.az.dev.ui.pages.CrushAnalyzerPage.MessageData;
import bgu.csp.az.dev.ui.pages.CrushAnalyzerPage.ScenarioPartFullData;
import java.awt.event.MouseEvent;
import java.util.LinkedList;

/**
 *
 * @author bennyl
 */
public class ScenarioPartView extends javax.swing.JPanel {

    LinkedList<Listener> listeners = new LinkedList<Listener>();
    ScenarioPartFullData model;

    /** Creates new form ScenarioPartView */
    public ScenarioPartView() {
        initComponents();
    }

    public void setModel(ScenarioPartFullData model) {
        this.model = model;

        agtName.setText(model.overview.mdata.receiver);
        rcvmsgName.setText(model.overview.mdata.name);
        sendagtName.setText(model.overview.mdata.sender);
        ccTime.setText("" + model.overview.handledCC);
        logList.setModel(model.logs);
        marglist.setModel(model.receivedArguments);
        msentlist.setModel(model.sentMessages);
    }

    public void addListener(Listener l) {
        listeners.add(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agtName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rcvmsgName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sendagtName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ccTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        marglist = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logList = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        msentlist = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 225));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText(" Selected Scenario Part Data:");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(255, 255, 225)));
        jLabel6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jLabel6, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 225));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Agent");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 8, 3);
        jPanel1.add(jLabel1, gridBagConstraints);

        agtName.setBackground(new java.awt.Color(51, 153, 255));
        agtName.setForeground(new java.awt.Color(51, 153, 255));
        agtName.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 8, 3);
        jPanel1.add(agtName, gridBagConstraints);

        jLabel2.setText("Received Message");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 8, 3);
        jPanel1.add(jLabel2, gridBagConstraints);

        rcvmsgName.setBackground(new java.awt.Color(51, 153, 255));
        rcvmsgName.setForeground(new java.awt.Color(51, 153, 255));
        rcvmsgName.setText("CPA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 8, 3);
        jPanel1.add(rcvmsgName, gridBagConstraints);

        jLabel3.setText("From Agent");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 8, 3);
        jPanel1.add(jLabel3, gridBagConstraints);

        sendagtName.setBackground(new java.awt.Color(51, 153, 255));
        sendagtName.setForeground(new java.awt.Color(51, 153, 255));
        sendagtName.setText("330");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 8, 1);
        jPanel1.add(sendagtName, gridBagConstraints);

        jLabel4.setText("At");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 8, 3);
        jPanel1.add(jLabel4, gridBagConstraints);

        ccTime.setBackground(new java.awt.Color(51, 153, 255));
        ccTime.setForeground(new java.awt.Color(51, 153, 255));
        ccTime.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 8, 3);
        jPanel1.add(ccTime, gridBagConstraints);

        jLabel5.setText("cc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 3);
        jPanel1.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 255)));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/message-args.png"))); // NOI18N
        jLabel7.setText("Message Arguments Received");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel3.add(jLabel7, gridBagConstraints);

        jScrollPane1.setBorder(null);

        marglist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        marglist.setSelectionBackground(new java.awt.Color(255, 255, 204));
        marglist.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(marglist);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel8.setForeground(new java.awt.Color(102, 153, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/log.png"))); // NOI18N
        jLabel8.setText("Logs Written");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel4.add(jLabel8, gridBagConstraints);

        jScrollPane2.setBorder(null);

        logList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        logList.setSelectionBackground(new java.awt.Color(255, 255, 204));
        logList.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(logList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel9.setForeground(new java.awt.Color(102, 153, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/message-send.png"))); // NOI18N
        jLabel9.setText("Messages Sent");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel5.add(jLabel9, gridBagConstraints);

        jScrollPane3.setBorder(null);

        msentlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        msentlist.setSelectionBackground(new java.awt.Color(255, 255, 204));
        msentlist.setSelectionForeground(new java.awt.Color(102, 102, 102));
        msentlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msentlistMouseClicked(evt);
            }
        });
        msentlist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                msentlistValueChanged(evt);
            }
        });
        msentlist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msentlistKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(msentlist);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void msentlistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_msentlistValueChanged
    }//GEN-LAST:event_msentlistValueChanged

    private void msentlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msentlistMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            fireMessageJumpRequest((MessageData) msentlist.getModel().getElementAt(msentlist.getSelectedIndex()));
        }
    }//GEN-LAST:event_msentlistMouseClicked

    private void msentlistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msentlistKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            fireMessageJumpRequest((MessageData) msentlist.getModel().getElementAt(msentlist.getSelectedIndex()));
        }
    }//GEN-LAST:event_msentlistKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agtName;
    private javax.swing.JLabel ccTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList logList;
    private javax.swing.JList marglist;
    private javax.swing.JList msentlist;
    private javax.swing.JLabel rcvmsgName;
    private javax.swing.JLabel sendagtName;
    // End of variables declaration//GEN-END:variables

    private void fireMessageJumpRequest(MessageData messageData) {
        for (Listener l : listeners) {
            l.onMessageJumpRequested(messageData);
        }
    }

    public static interface Listener {

        void onMessageJumpRequested(MessageData jumpTo);
    }
}
