/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BarChartView.java
 *
 * Created on 18/08/2011, 12:45:09
 */
package bam.utils.ui.graph;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;

/**
 *
 * @author bennyl
 */
public class BarChartView extends javax.swing.JPanel implements BarChartModel.Listener{
    private BarRenderer barrenderer;
    private JFreeChart jfreechart;
    private ChartPanel chartPanel;

    /** Creates new form BarChartView */
    public BarChartView() {
        initComponents();
    }
    
    public void setModel(BarChartModel model){
        removeAll();
        setLayout(new BorderLayout());
        chartPanel = new ChartPanel(createChart(model));
        add(chartPanel);
        model.addListener(this);
    }

    private JFreeChart createChart(BarChartModel model) {
        jfreechart = ChartFactory.createBarChart(model.getChartTitle(), model.getxAxeTitle(), model.getyAxeTitle(), model.getChartModel(), PlotOrientation.VERTICAL, false, true, false);
        jfreechart.setBackgroundPaint(Color.white);
        CategoryPlot categoryplot = (CategoryPlot) jfreechart.getPlot();
        categoryplot.setBackgroundPaint(Color.white);
        
        categoryplot.setDomainGridlinePaint(new Color(200, 200, 200));
        categoryplot.setDomainGridlinesVisible(true);
        categoryplot.setRangeGridlinePaint(new Color(200, 200, 200));
        categoryplot.setRangeGridlinesVisible(true);
        
        //NumberAxis numberaxis = (NumberAxis) categoryplot.getRangeAxis();
        //numberaxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        barrenderer = (BarRenderer) categoryplot.getRenderer();
        barrenderer.setDrawBarOutline(true);
        barrenderer.setBarPainter(new StandardBarPainter());
        //CategoryAxis categoryaxis = categoryplot.getDomainAxis();
        //categoryaxis.setCategoryLabelPositions(CategoryLabelPositions.createUpRotationLabelPositions(0.52359877559829882D));
        
        CategoryAxis domainAxis = categoryplot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
        domainAxis.setTickMarksVisible(true);
        
        for (String bar : model.getBars()) onBarAdded(model, bar);
        
        return jfreechart;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

   
    @Override
    public void onBarChanged(BarChartModel source, String barName, long newValue) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void onBarAdded(BarChartModel source, String barName) {
        final int rowIndex = source.getChartModel().getColumnIndex(barName);
        barrenderer.setSeriesItemLabelsVisible(rowIndex, true);
        barrenderer.setSeriesPaint(rowIndex, new Color(160,200,255));
    }
}
