/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExecutionStatisticalView.java
 *
 * Created on 18/08/2011, 10:41:40
 */
package bgu.csp.az.dev.pui.sgrp;

import bc.dsl.PageDSL;
import bc.swing.pfrm.Page;
import bc.swing.pfrm.PageView;
import bc.swing.pfrm.params.ParamModel;
import bc.swing.pfrm.params.ParamModel.Listener;
import java.awt.Color;
import org.jdesktop.swingx.painter.RectanglePainter;

/**
 *
 * @author bennyl
 */
public class StatisticsView extends javax.swing.JPanel implements PageView {

    public static final String GRAPHS_TREE_ROLE = "GRAPHS TREE ROLE";

    /** Creates new form ExecutionStatisticalView */
    public StatisticsView() {
        initComponents();
        descriptionLabel.setBackgroundPainter(new RectanglePainter(new Color(245, 245, 245), null));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        graphsContainetPan = new javax.swing.JPanel();
        graphPan = new javax.swing.JPanel();
        chartsPanel = new javax.swing.JPanel();
        nographLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        descriptionLabel = new org.jdesktop.swingx.JXLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        graphsContainetPan.setBackground(new java.awt.Color(245, 245, 245));
        graphsContainetPan.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        graphsContainetPan.add(graphPan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(graphsContainetPan, gridBagConstraints);

        chartsPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartsPanel.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        nographLabel.setFont(new java.awt.Font("Tahoma", 0, 18));
        nographLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nographLabel.setText("No Graphs To Show - Select one from the List");
        nographLabel.setMaximumSize(new java.awt.Dimension(9999999, 22));
        nographLabel.setPreferredSize(new java.awt.Dimension(99999, 22));
        chartsPanel.add(nographLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel1.add(chartsPanel, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(245, 245, 245));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/information-frame.png"))); // NOI18N
        jLabel2.setText("Description");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(245, 245, 245)));
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 24));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        jPanel1.add(jLabel2, gridBagConstraints);

        descriptionLabel.setBackground(new java.awt.Color(245, 245, 245));
        descriptionLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 5, new java.awt.Color(245, 245, 245)));
        descriptionLabel.setForeground(new java.awt.Color(51, 102, 255));
        descriptionLabel.setText("Description Here");
        descriptionLabel.setLineWrap(true);
        descriptionLabel.setMaximumSize(new java.awt.Dimension(200, 0));
        descriptionLabel.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        jPanel1.add(descriptionLabel, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartsPanel;
    private org.jdesktop.swingx.JXLabel descriptionLabel;
    private javax.swing.JPanel graphPan;
    private javax.swing.JPanel graphsContainetPan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nographLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setModel(Page model) {
        PageDSL.fillByRole(model, graphPan, GRAPHS_TREE_ROLE);
        model.getParamsWithRole(GRAPHS_TREE_ROLE).get(0).addSelectionListner(new Listener() {

            @Override
            public void onChange(ParamModel source, Object newValue, Object deltaHint) {
                descriptionLabel.setText(source.getPage().getModel().provideParamValueDescription(source.getName(), newValue));
            }
        });
    }

    @Override
    public void onDispose() {
//        throw new UnsupportedOperationException("Not supported yet.");
    }
}
