/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PageForm.java
 *
 * Created on Sep 11, 2011, 12:37:56 PM
 */
package bc.swing.pfrm.views;

import bc.swing.pfrm.Page;
import bc.swing.pfrm.PageView;
import bc.swing.pfrm.ano.ViewHints;
import bc.swing.pfrm.params.ParamModel;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author BLutati
 */
public class FormLayout extends javax.swing.JPanel implements PageView {

    Page model;
    public Set<String> exclude;

    
    /** Creates new form PageForm */
    public FormLayout() {
        initComponents();
        exclude = new HashSet<String>();
    }

    /**
     * must be called before setModel();
     * @param fields
     */
    public void excludeParams(String... fields) {
        exclude.addAll(Arrays.asList(fields));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void setModel(Page model) {
        this.model = model;
        List<ParamModel> params = model.getParams();
        for (ParamModel param : params) {
            if (!exclude.contains(param.getName())) {
                addLabel(param.getName(), param.getIcon());
                addValueView(param.getDefaultView(), param.getViewHints());
            }
        }

        sealLayout();
        validate();
        repaint();
    }

    private void addLabel(String name, ImageIcon icon) {
        JLabel lbl = new JLabel();
        lbl.setOpaque(true);
        lbl.setText(name);
        lbl.setIcon(icon);
        lbl.setBackground(new Color(245, 245, 245));
        GridBagConstraints cons = new GridBagConstraints();
        cons.fill = GridBagConstraints.BOTH;
        cons.gridx = 0;
        cons.insets = new Insets(5, 5, 0, 5);
        add(lbl, cons);
    }

    
    private void addValueView(JComponent defaultView, ViewHints viewHints) {
        GridBagConstraints cons = new GridBagConstraints();
        cons.gridx = 1;
        cons.insets = new Insets(5, 5, 0, 5);
        cons.weightx = 1;
        cons.fill = GridBagConstraints.BOTH;
        if (viewHints.heightExpandPrecentage() > 0){
            cons.weighty = 100.0/viewHints.heightExpandPrecentage();
        }
        
        add(defaultView, cons);
    }
    
    private void sealLayout(){
        JPanel sidepan = new JPanel();
        sidepan.setBackground(new java.awt.Color(245, 245, 245));
        GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 500;
        gbc.fill = java.awt.GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 0, 0, 0);
        add(sidepan, gbc);
    }

    public void onDispose() {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
