/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PagePanel.java
 *
 * Created on 15/09/2011, 03:25:25
 */
package bc.swing.pfrm.views;

import bc.swing.pfrm.Page;
import bc.swing.pfrm.PageView;
import bc.swing.pfrm.params.ParamModel;
import java.awt.BorderLayout;
import java.util.List;

/**
 *
 * @author bennyl
 */
public class SingleParamPageView extends javax.swing.JPanel implements PageView{

    /** Creates new form PagePanel */
    public SingleParamPageView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setModel(Page model) {  
        List<ParamModel> params = model.getParams();
        add(params.get(0).getDefaultView(), BorderLayout.CENTER);
        validate();
        repaint();
    }

    public void onDispose() {
    }
}
