/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatisticsScreen.java
 *
 * Created on 24/11/2011, 16:25:21
 */
package bgu.csp.az.dev.ui;

import bc.ui.swing.listeners.SelectionListener;
import bc.ui.swing.lists.OptionList;
import bc.ui.swing.visuals.Visual;
import bgu.csp.az.api.infra.Experiment;
import bgu.csp.az.api.infra.Round;
import bgu.csp.az.api.infra.stat.StatisticCollector;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author bennyl
 */
public class StatisticsScreen extends javax.swing.JPanel {

    OptionList availableStatisticsList;
    OptionList roundsList;

    /** Creates new form StatisticsScreen */
    public StatisticsScreen() {
        initComponents();
        //STAT
        availableStatisticsList = new OptionList();
        statScroll.setViewportView(availableStatisticsList);

        //ROUND
        roundsList = new OptionList();
        roundScroll.setViewportView(roundsList);

        statScroll.getViewport().setOpaque(false);
        varscrolls.getViewport().setOpaque(false);
        roundScroll.getViewport().setOpaque(false);

        //TESTING 
//        availableStatisticsList.add("stat 1");
//        availableStatisticsList.add("stat 2");
//        
//        roundsList.add("stat 1");
//        roundsList.add("stat 2");
//        
//        vars.add(new VariableMetadata("test1", "this is test 1", 5, Integer.class));
//        vars.add(new VariableMetadata("test2", "this is test 2", 5, Integer.class));
//        vars.add(new VariableMetadata("test3", "this is test 3", 5, Integer.class));

    }

    public void setModel(Experiment exp) {
        availableStatisticsList.getSelectionListeners().addListener(new SelectionListener() {

            @Override
            public void onSelectionChanged(Object source, List selectedItems) {
                varsDataPan.unSetData();
                
                if (!selectedItems.isEmpty()){
                    StatisticCollector sc = (StatisticCollector) ((Visual)selectedItems.get(0)).getItem();
                    if (sc.provideExpectedVariables().length > 0){
                        vars.setModel(sc.provideExpectedVariables());
                        varsDataPan.setData(varscrolls);
                        
                    }
                }
                
            }
        });
        
        roundsList.getSelectionListeners().addListener(new SelectionListener() {

            @Override
            public void onSelectionChanged(Object source, List selectedItems) {
                availableStatisticsList.clear();

                if (!selectedItems.isEmpty()) {

                    Round selected = ((Round) ((Visual) selectedItems.get(0)).getItem());
                    availableStatisticsList.setItems(Visual.adapt(selected.getRegisteredStatisticCollectors(), new Visual.VisualGen() {

                        @Override
                        public Visual gen(Object it) {
                            StatisticCollector sc = (StatisticCollector) it;
                            return new Visual(it, sc.getName(), "", null);
                        }
                    }));
                }
            }
        });

        roundsList.setItems(Visual.adapt(exp.getRounds(), new Visual.VisualGen() {

            @Override
            public Visual gen(Object it) {
                Round r = (Round) it;
                return new Visual(it, r.getName(), "", null);
            }
        }));

    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setContentPane(new StatisticsScreen());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        resultsPan = new javax.swing.JSplitPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        varscrolls = new javax.swing.JScrollPane();
        vars = new bc.ui.swing.configurable.VariablesEditor();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        roundScroll = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        statScroll = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        varsDataPan = new bc.ui.swing.useful.DataPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nodataPan = new bc.ui.swing.useful.DataPanel();

        resultsPan.setResizeWeight(0.65);
        resultsPan.setLeftComponent(jPanel13);
        resultsPan.setRightComponent(jPanel14);

        varscrolls.setBorder(null);
        varscrolls.setOpaque(false);
        varscrolls.setViewportView(vars);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanel12.setBackground(new java.awt.Color(120, 120, 120));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Configuration");
        jPanel12.add(jLabel9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel12, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(102, 180));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setMinimumSize(new java.awt.Dimension(180, 10));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 12));
        jLabel6.setText("Select Round To Analayze");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel6, gridBagConstraints);

        roundScroll.setBorder(null);
        roundScroll.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(roundScroll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/lineWithNumber1.png"))); // NOI18N
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, new java.awt.GridBagConstraints());

        jPanel4.setBackground(new java.awt.Color(232, 232, 232));
        jPanel4.setMinimumSize(new java.awt.Dimension(240, 52));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12));
        jLabel7.setText("Select Statistic");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel7, gridBagConstraints);

        statScroll.setBorder(null);
        statScroll.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel4.add(statScroll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/lineWithNumber2.png"))); // NOI18N
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, new java.awt.GridBagConstraints());

        jPanel6.setBackground(new java.awt.Color(220, 220, 220));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 12));
        jLabel8.setText("Configure Analyzer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jLabel8, gridBagConstraints);

        varsDataPan.setNoDataText("No Configuration Needed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel6.add(varsDataPan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel6, gridBagConstraints);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/lineWithNumber3.png"))); // NOI18N
        jPanel8.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8, new java.awt.GridBagConstraints());

        jPanel7.setBackground(new java.awt.Color(210, 210, 210));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jXHyperlink1.setForeground(new java.awt.Color(0, 102, 204));
        jXHyperlink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/statistics-collection-view.png"))); // NOI18N
        jXHyperlink1.setText("Analyze");
        jXHyperlink1.setClickedColor(new java.awt.Color(0, 102, 204));
        jXHyperlink1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jXHyperlink1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jXHyperlink1.setUnclickedColor(new java.awt.Color(0, 102, 204));
        jXHyperlink1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel7.add(jXHyperlink1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel7, gridBagConstraints);

        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel9, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jPanel1, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(245, 245, 245));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(120, 120, 120)));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(120, 120, 120));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Analyzing Results");
        jPanel11.add(jLabel4);

        jPanel10.add(jPanel11, java.awt.BorderLayout.PAGE_START);
        jPanel10.add(nodataPan, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(jPanel10, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private bc.ui.swing.useful.DataPanel nodataPan;
    private javax.swing.JSplitPane resultsPan;
    private javax.swing.JScrollPane roundScroll;
    private javax.swing.JScrollPane statScroll;
    private bc.ui.swing.configurable.VariablesEditor vars;
    private bc.ui.swing.useful.DataPanel varsDataPan;
    private javax.swing.JScrollPane varscrolls;
    // End of variables declaration//GEN-END:variables
}
