package bgu.dcr.az.lab.data;
// Generated May 30, 2012 7:41:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private Articles articles;
     private Date creationDate;
     private byte[] content;

    public Comments() {
    }

    public Comments(Users users, Articles articles, Date creationDate, byte[] content) {
       this.users = users;
       this.articles = articles;
       this.creationDate = creationDate;
       this.content = content;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Articles getArticles() {
        return this.articles;
    }
    
    public void setArticles(Articles articles) {
        this.articles = articles;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }




}


