/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PieChart.java
 *
 * Created on 09/03/2011, 05:10:57
 */

package bam.utils.ui.graph;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author bennyl
 */
public class PieChart extends javax.swing.JPanel {

    private JFreeChart chart;

    /** Creates new form PieChart */
    public PieChart() {
        initComponents();
    }

    /**
     * Creates a sample chart.
     *
     * @param dataset  the dataset.
     *
     * @return A chart.
     */
    private JFreeChart createChart(PieChartModel model) {

        JFreeChart chart = ChartFactory.createPieChart3D(
            model.getChartTitle(),  // chart title
            model.getChartModel(),                // data
            true,                   // include legend
            true,
            false
        );

        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        plot.setNoDataMessage("No data to display");

        plot.setBackgroundPaint(Color.white);

        return chart;

    }

    
    public void setModel(PieChartModel model){
        chart = createChart(model);

        setLayout(new BorderLayout());
        ChartPanel chartPanel = new ChartPanel(chart);
        add(chartPanel, BorderLayout.CENTER);
        
    }

    public void setTitle(String title){
        chart.setTitle(title);
        chart.getTitle().setFont(new java.awt.Font("Showcard Gothic", 0, 14));
    }

    public String getTitle(){
        return chart.getTitle().getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
